Task.create task: "Build a birdhouse and install it somewhere", deadline: "within the next month", status: "rad"
Task.create task: "Visit the smallest town in your state", deadline: "within the next year", status: "rad"
Task.create task: "Climb a small to medium-sized mountain", deadline: "within the next year", status: "rad"
Task.create task: "Take a road trip with the person in your friend group who you hang out with the least", deadline: "(in the next 6 months)", status: "rad"
Task.create task: "Send a letter to the editor about the first thing that you think of after reading this", deadline: "(in the next 12 hours)", status: "rad"
Task.create task: "Send a postcard to someone you know in a foreign country", deadline: "within the next 14 days", status: "rad"
Task.create task: "Sew, knit, or otherwise make yourself an article of clothing and wear it", deadline: "within the next two months", status: "rad"
Task.create task: "Find an interesting location outdoors and stay there for at least 6 hours", deadline: "within the next two weeks", status: "rad"
Task.create task: "Dance to classical music with at least one person watching", deadline: "(in the next week)", status: "rad"
Task.create task: "Write a letter to yourself to be opened in 7 days.  Put it in the mail at your local post office", deadline: "by the end of today.", status: "rad"
Task.create task: "Spend exactly 2 hours thinking about life. No cell phone, no distractions.", deadline: "(within the next week)", status: "rad"
Task.create task: "Learn to recognize 5 new types of plant", deadline: "within the next month.", status: "rad"